name: License Checking
on:
  push:
    branches:
      - 'main'
      - 'develop'
      - 'release-**'
  pull_request:
    branches:
      - 'main'
      - 'develop'
      - 'release-**'
  issue_comment:
    types: [created]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Log GitHub Event Name
        if: github.event_name == 'issue_comment'
        run: >
            echo "This workflow was triggered by an issue comment. Event: ${{ github.event_name }}"

      - name: Log Something Else
        if: github.event_name != 'issue_comment'
        run: >
            echo "This workflow was not triggered by an issue comment. Event: ${{ github.event_name }}"


  # Documentation: https://github.com/eclipse-dash/dash-licenses#reusable-github-workflow-for-automatic-license-check-and-ip-team-review-requests
  eclipse-dash-license-tool-run:
    name: Eclipse Dash License Tool
    uses: eclipse-dash/dash-licenses/.github/workflows/mavenLicenseCheck.yml@master
    with:
      projectId: technology.cbi
    secrets:
      gitlabAPIToken: ${{ secrets.ECLIPSE_GITLAB_API_TOKEN }} # We should ask Eclipse to add this secret at some point. Currently, we do not want to do automatic license vetting submission.
